### ISSUE TITLE
You forgot to check in .meteor folder

### ISSUE THREAD

**Issue by mikkelking** [gkrizek/ghostwall#1]
I am interested to have a look at your work,

In order to run it, the .meteor folder is needed - can you add this please?

Mike

**Comment by gkrizek** [comment]
My apologies @mikkelking. It's been a while since I have run Meteor so I forgot that's required.

I have added it back in now. 

Thanks.

**Comment by MikeDBR** [comment]
Graeme,
That helps, i now have it running, is there any chance you could provide some 'getting started' info in the readme? I commented out the pem key references, and set it to non-production.

It redirects to ghostwall.io, which I stopped, but all I get is a purple screen - will it run on the desktop, or is it a device only app?

Thanks

Mike

**Comment by gkrizek** [comment]
@MikeDBR Yeah, I'll try to do that when I get some time. Sorry for the confusion, I didn't mean for the to be a tutorial, simply just a code dump for people to look at. I'll try to add some instructions.

You can either run it in an Apple Device Simulator or a real Apple Device as is. Or to run it on desktop, you just disable the `isCordova` check in the routes:

https://github.com/gkrizek/ghostwall/blob/master/client/routes.js#L39
https://github.com/gkrizek/ghostwall/blob/master/client/routes.js#L180

That is what's causing the redirect. I did this because I didn't want people to be accessing the app on the web, only in the mobile app.

**Comment by gkrizek** [comment]
@MikeDBR I updated the `README.md` with some basic getting started. Were you able to run it after commenting out those lines?
